service: serverless-fastify-typescript-starter
frameworkVersion: "3"

provider:
  name: aws
  region: eu-central-1
  runtime: nodejs18.x

package:
  patterns:
    - '!./**'
    - ./dist/bundle.js

functions:
  api:
    handler: dist/bundle.handler
    events:
      - httpApi: '*'
